package net.uchoice.travelgift.vote.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import net.uchoice.travelgift.vote.entity.ArticleImage;

@Mapper
public interface ArticleImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_image
     *
     * @mbggenerated
     */
    int insert(ArticleImage record);
    
    int batchInsert(List<ArticleImage> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_image
     *
     * @mbggenerated
     */
    ArticleImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_image
     *
     * @mbggenerated
     */
    List<ArticleImage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleImage record);
}