#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: net.uchoice.travelgift.vote.entity
  mapperLocations: classpath*:mappers/*.xml
#  config-location: classpath*:/mybatis/mybatis-config.xml


---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://5698f162172b1.sh.cdb.myqcloud.com:16130/travelgift
    username: dev
    password: uchoice2018
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
#微信配置
wechart:
  appId: wx07f9401307a023bd
  token: uchoice2018
  portal: <xml><Articles><item><Title><![CDATA[title1]]></Title> <Description><![CDATA[description1]]></Description><PicUrl><![CDATA[http://baidu.com/11.png]]></PicUrl><Url><![CDATA[url]]></Url></item><item><Title><![CDATA[title]]></Title><Description><![CDATA[description]]></Description><PicUrl><![CDATA[picurl]]></PicUrl><Url><![CDATA[url]]></Url></item></Articles></xml>