#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: net.uchoice.travelgift.vote.entity
  mapperLocations: classpath*:mappers/*.xml
#  config-location: classpath*:/mybatis/mybatis-config.xml


---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://5698f162172b1.sh.cdb.myqcloud.com:16130/travelgift
    username: dev
    password: uchoice2018
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
#微信配置
wechart:
  appId: wx07f9401307a023bd
  token: uchoice2018
  portal: <xml><Articles><item><Title><![CDATA[欢迎来到礼游记]]></Title> <Description><![CDATA[欢迎来到礼游记，在这里可以发现更多乐趣]]></Description><PicUrl><![CDATA[https://mmbiz.qpic.cn/mmbiz_jpg/zMOic5iahb0u0MwGwP0CBl6WOsxmY9DcxV865w9fSVOdA5PzzRgtyFNsbQiauviaAvHTW6gvdJ3RmQib6CgUtxeQn8Q/0?wx_fmt=jpeg]]></PicUrl><Url><![CDATA[http://www.baidu.com]]></Url></item><item><Title><![CDATA[五一活动 | 礼游送好礼]]></Title><Description><![CDATA[五一出游随手拍，精彩礼品等你拿]]></Description><PicUrl><![CDATA[https://mmbiz.qpic.cn/mmbiz_png/zMOic5iahb0u0MwGwP0CBl6WOsxmY9DcxVMRRrFATvt8SiaCKJibH7D7xSrcjgF6icgUoWhLDFKA6UoDN2zhVKUMicmA/0?wx_fmt=png]]></PicUrl><Url><![CDATA[https://mmbiz.qpic.cn/mmbiz_png/zMOic5iahb0u0MwGwP0CBl6WOsxmY9DcxV53Ria7JHZMPqPtIokTgpEw6aex4A4p265dQGptcj8xOgp7sYoEkLcBA/0?wx_fmt=png]]></Url></item></Articles></xml>