package net.uchoice.travelgift.vote.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;

import net.uchoice.travelgift.vote.entity.Article;
import net.uchoice.travelgift.vote.util.JsonUtils;

public class ArticleVo implements Serializable {
	
	private Integer id;

	private String title;

	private List<ContentItemVo> content;
	
	private CrowdVo crowds;
	
	private CrowdVo scenes;

	private Integer votes;
	
	private Integer status;

	private String author;

	private Date createDate;

	private Date updateDate;

	private static final long serialVersionUID = 1L;
	
	public ArticleVo() {
	}
	
	public ArticleVo(Article article) {
		this.id = article.getId();
		this.title = article.getTitle();
		this.crowds = JsonUtils.parse(article.getCrowd(), CrowdVo.class);
		this.scenes = JsonUtils.parse(article.getScene(), CrowdVo.class);
		this.votes = article.getVotes();
		this.status = article.getStatus();
		this.author = article.getAuthor();
		this.createDate = article.getCreateDate();
		this.updateDate = article.getUpdateDate();
		this.content = JsonUtils.parse(article.getContent(), 
				JsonUtils.getCollectionType(List.class, ContentItemVo.class));
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public List<ContentItemVo> getContent() {
		return content;
	}

	public void setContent(List<ContentItemVo> content) {
		this.content = content;
	}

	public CrowdVo getCrowds() {
		return crowds;
	}

	public void setCrowds(CrowdVo crowds) {
		this.crowds = crowds;
	}

	public CrowdVo getScenes() {
		return scenes;
	}

	public void setScenes(CrowdVo scenes) {
		this.scenes = scenes;
	}

	public Integer getVotes() {
		return votes;
	}

	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}
	
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", title=").append(title);
		sb.append(", content=").append(content);
		sb.append(", votes=").append(votes);
		sb.append(", author=").append(author);
		sb.append(", createDate=").append(createDate);
		sb.append(", updateDate=").append(updateDate);
		sb.append(", crowds=").append(crowds);
		sb.append(", scenes=").append(scenes);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
	

}
