package net.uchoice.vote.entity;

import java.io.Serializable;
import java.util.Date;

public class VoteHis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_his.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_his.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_his.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vote_his.vote_date
     *
     * @mbggenerated
     */
    private Date voteDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vote_his
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_his.id
     *
     * @return the value of t_vote_his.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_his.id
     *
     * @param id the value for t_vote_his.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_his.article_id
     *
     * @return the value of t_vote_his.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_his.article_id
     *
     * @param articleId the value for t_vote_his.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_his.user_id
     *
     * @return the value of t_vote_his.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_his.user_id
     *
     * @param userId the value for t_vote_his.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vote_his.vote_date
     *
     * @return the value of t_vote_his.vote_date
     *
     * @mbggenerated
     */
    public Date getVoteDate() {
        return voteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vote_his.vote_date
     *
     * @param voteDate the value for t_vote_his.vote_date
     *
     * @mbggenerated
     */
    public void setVoteDate(Date voteDate) {
        this.voteDate = voteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vote_his
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", articleId=").append(articleId);
        sb.append(", userId=").append(userId);
        sb.append(", voteDate=").append(voteDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}