package net.uchoice.travelgift.vote.entity;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Article implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.title
	 *
	 * @mbggenerated
	 */
	@NotBlank(message = "标题不能为空")
	@Size(min = 1, max = 32, message = "标题最大长度不能超过32")
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.content
	 *
	 * @mbggenerated
	 */
	@NotBlank(message = "内容不能为空")
	@Size(min = 1, max = 512, message = "内容最大长度不能超过512")
	private String content;
	
	
	private String crowd;
	
	private String scene;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.votes
	 *
	 * @mbggenerated
	 */
	private Integer votes;
	/**
	 * 
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.create_by
	 *
	 * @mbggenerated
	 */
	private String author;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_article.create_date
	 *
	 * @mbggenerated
	 */
	private Date createDate;

	private Date updateDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_article
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.id
	 *
	 * @return the value of t_article.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.id
	 *
	 * @param id
	 *            the value for t_article.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.title
	 *
	 * @return the value of t_article.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.title
	 *
	 * @param title
	 *            the value for t_article.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.content
	 *
	 * @return the value of t_article.content
	 *
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.content
	 *
	 * @param content
	 *            the value for t_article.content
	 *
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.votes
	 *
	 * @return the value of t_article.votes
	 *
	 * @mbggenerated
	 */
	public Integer getVotes() {
		return votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.votes
	 *
	 * @param votes
	 *            the value for t_article.votes
	 *
	 * @mbggenerated
	 */
	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.create_by
	 *
	 * @return the value of t_article.create_by
	 *
	 * @mbggenerated
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.create_by
	 *
	 * @param author
	 *            the value for t_article.author
	 *
	 * @mbggenerated
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_article.create_date
	 *
	 * @return the value of t_article.create_date
	 *
	 * @mbggenerated
	 */
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_article.create_date
	 *
	 * @param createDate
	 *            the value for t_article.create_date
	 *
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCrowd() {
		return crowd;
	}

	public void setCrowd(String crowd) {
		this.crowd = crowd;
	}

	public String getScene() {
		return scene;
	}

	public void setScene(String scene) {
		this.scene = scene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_article
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", title=").append(title);
		sb.append(", content=").append(content);
		sb.append(", votes=").append(votes);
		sb.append(", author=").append(author);
		sb.append(", createDate=").append(createDate);
		sb.append(", updateDate=").append(updateDate);
		sb.append(", crowd=").append(crowd);
		sb.append(", scene=").append(scene);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}